create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  discord_user_id text unique not null,
  discord_username text,
  discord_avatar_url text,
  access_status text not null default 'active' check (access_status in ('active','review','blocked')),
  blocked_reason text,
  blocked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.auth_devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_install_hash text not null,
  ip_hash text,
  asn text,
  network_name text,
  network_type text,
  country_code text,
  last_seen_at timestamptz not null default now(),
  unique (user_id, device_install_hash)
);

create table if not exists public.auth_networks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  ip_hash text,
  asn text,
  network_name text,
  network_type text,
  mobile boolean,
  country_code text,
  last_seen_at timestamptz not null default now(),
  unique (user_id, ip_hash, asn)
);

create table if not exists public.access_blocks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  matched_user_id uuid references public.profiles(id) on delete set null,
  block_code text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.auth_login_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  outcome text not null,
  reason text,
  device_install_hash text,
  ip_hash text,
  asn text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.auth_devices enable row level security;
alter table public.auth_networks enable row level security;
alter table public.access_blocks enable row level security;
alter table public.auth_login_logs enable row level security;

drop policy if exists profiles_read_own on public.profiles;
create policy profiles_read_own on public.profiles for select using (auth.uid() = id);
drop policy if exists profiles_update_safe on public.profiles;
revoke insert, update, delete on public.profiles from anon, authenticated;

revoke all on public.auth_devices from anon, authenticated;
revoke all on public.auth_networks from anon, authenticated;
revoke all on public.access_blocks from anon, authenticated;
revoke all on public.auth_login_logs from anon, authenticated;
