create table if not exists public.admin_action_logs (
  id bigint generated by default as identity primary key,
  admin_user_id text not null,
  admin_kind text not null check (admin_kind in ('bootstrap', 'discord')),
  target_user_id text,
  target_country_key text,
  action_kind text not null check (action_kind in ('REVOKE_COUNTRY_OWNERSHIP', 'DENY_COUNTRY_ACCESS', 'SUSPEND_ALL_PLAY', 'BLOCK_ACCOUNT')),
  reason text not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.admin_action_logs enable row level security;
revoke all on public.admin_action_logs from anon, authenticated;
