create table if not exists public.economy_rules (
  singleton boolean primary key default true check (singleton),
  settlement_interval_days integer not null default 30 check (settlement_interval_days between 1 and 365),
  budget_min integer not null default 0,
  budget_max integer not null default 100,
  budget_step integer not null default 1 check (budget_step = 1),
  calculation_parameters jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  check (budget_min < budget_max)
);

insert into public.economy_rules (singleton) values (true)
on conflict (singleton) do nothing;

create table if not exists public.country_economies (
  country_key text primary key,
  gdp numeric check (gdp >= 0),
  nominal_growth_rate numeric,
  inflation_rate numeric,
  unemployment_rate numeric check (unemployment_rate between 0 and 100),
  national_debt numeric check (national_debt >= 0),
  foreign_reserves numeric check (foreign_reserves >= 0),
  national_income numeric check (national_income >= 0),
  total_expenditure numeric check (total_expenditure >= 0),
  base_production_capacity numeric check (base_production_capacity >= 0),
  production_capacity_modifier numeric,
  domestic_capacity_used numeric check (domestic_capacity_used >= 0),
  research_capacity numeric check (research_capacity >= 0),
  budget_fulfillment_rate numeric check (budget_fulfillment_rate between 0 and 100),
  nominal_tax_rate numeric check (nominal_tax_rate between 0 and 100),
  tax_collection_efficiency numeric check (tax_collection_efficiency between 0 and 100),
  industrial_structure jsonb,
  current_budget jsonb,
  draft_budget jsonb,
  next_budget jsonb,
  next_budget_world_date date,
  updated_at timestamptz not null default now()
);

create table if not exists public.economy_resource_types (
  id text primary key,
  name_ko text unique not null,
  sort_order integer unique not null,
  active boolean not null default true
);

insert into public.economy_resource_types (id, name_ko, sort_order) values
  ('STEEL', '철강', 10),
  ('OIL', '석유', 20),
  ('COAL', '석탄', 30),
  ('FOOD', '식량', 40),
  ('RARE_MINERALS', '희귀광물', 50)
on conflict (id) do update set name_ko = excluded.name_ko, sort_order = excluded.sort_order;

create table if not exists public.country_resources (
  country_key text not null,
  resource_type_id text not null references public.economy_resource_types(id),
  stockpile numeric check (stockpile >= 0),
  production_per_period numeric check (production_per_period >= 0),
  domestic_use numeric check (domestic_use >= 0),
  export_limit numeric check (export_limit >= 0),
  is_public boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (country_key, resource_type_id)
);

create table if not exists public.economy_history (
  id bigint generated by default as identity primary key,
  country_key text not null,
  period_start date not null,
  period_end date not null,
  status text not null check (status in ('PREVIEW', 'APPLIED', 'BLOCKED_MISSING_DATA', 'FAILED')),
  snapshot jsonb not null default '{}'::jsonb,
  idempotency_key text unique not null,
  created_at timestamptz not null default now(),
  check (period_start <= period_end)
);

create table if not exists public.trade_proposals (
  id uuid primary key default gen_random_uuid(),
  proposer_country_key text not null,
  receiver_country_key text not null,
  status text not null default 'PENDING' check (status in ('DRAFT', 'PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'CANCELLED')),
  review_route text not null check (review_route in ('PLAYER', 'ADMIN')),
  proposed_start_world_date date not null,
  proposed_end_world_date date not null,
  settlement_interval_days integer not null check (settlement_interval_days between 1 and 365),
  response_deadline_world_date date not null,
  auto_renew boolean not null default false,
  allow_early_termination boolean not null default true,
  allow_partial_fulfillment boolean not null default false,
  idempotency_key text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (proposer_country_key <> receiver_country_key),
  check (proposed_start_world_date < proposed_end_world_date),
  check (response_deadline_world_date <= proposed_start_world_date)
);

create unique index if not exists trade_proposals_one_pending_pair
  on public.trade_proposals(proposer_country_key, receiver_country_key)
  where status = 'PENDING';

create table if not exists public.trade_proposal_lines (
  id bigint generated by default as identity primary key,
  proposal_id uuid not null references public.trade_proposals(id) on delete cascade,
  from_country_key text not null,
  to_country_key text not null,
  asset_type text not null check (asset_type in ('RESOURCE', 'PRODUCTION_CAPACITY')),
  resource_type_id text references public.economy_resource_types(id),
  amount_per_settlement numeric not null check (amount_per_settlement > 0),
  created_at timestamptz not null default now(),
  check (from_country_key <> to_country_key),
  check ((asset_type = 'RESOURCE' and resource_type_id is not null) or (asset_type = 'PRODUCTION_CAPACITY' and resource_type_id is null))
);

create table if not exists public.trade_agreements (
  id uuid primary key default gen_random_uuid(),
  created_from_proposal_id uuid unique not null references public.trade_proposals(id),
  country_a_key text not null,
  country_b_key text not null,
  status text not null check (status in ('SCHEDULED', 'ACTIVE', 'SUSPENDED', 'BREACHED', 'EXPIRED', 'TERMINATED', 'CANCELLED')),
  starts_world_date date not null,
  ends_world_date date not null,
  settlement_interval_days integer not null check (settlement_interval_days between 1 and 365),
  next_settlement_world_date date,
  auto_renew boolean not null default false,
  allow_early_termination boolean not null default true,
  allow_partial_fulfillment boolean not null default false,
  terms jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (country_a_key <> country_b_key),
  check (starts_world_date <= ends_world_date)
);

create table if not exists public.trade_agreement_lines (
  id bigint generated by default as identity primary key,
  agreement_id uuid not null references public.trade_agreements(id) on delete cascade,
  from_country_key text not null,
  to_country_key text not null,
  asset_type text not null check (asset_type in ('RESOURCE', 'PRODUCTION_CAPACITY')),
  resource_type_id text references public.economy_resource_types(id),
  amount_per_settlement numeric not null check (amount_per_settlement > 0),
  check (from_country_key <> to_country_key),
  check ((asset_type = 'RESOURCE' and resource_type_id is not null) or (asset_type = 'PRODUCTION_CAPACITY' and resource_type_id is null))
);

create table if not exists public.trade_settlements (
  id uuid primary key default gen_random_uuid(),
  agreement_id uuid not null references public.trade_agreements(id) on delete cascade,
  scheduled_world_date date not null,
  executed_world_date date,
  status text not null check (status in ('PENDING', 'COMPLETED', 'FAILED', 'PARTIAL')),
  result jsonb not null default '{}'::jsonb,
  idempotency_key text unique not null,
  created_at timestamptz not null default now(),
  unique (agreement_id, scheduled_world_date)
);

create table if not exists public.trade_history (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  country_key text not null,
  related_country_key text,
  proposal_id uuid references public.trade_proposals(id) on delete set null,
  agreement_id uuid references public.trade_agreements(id) on delete set null,
  action_type text not null,
  details jsonb not null default '{}'::jsonb,
  world_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.trade_notifications (
  id uuid primary key default gen_random_uuid(),
  country_key text not null,
  counterpart_country_key text not null,
  proposal_id uuid references public.trade_proposals(id) on delete cascade,
  agreement_id uuid references public.trade_agreements(id) on delete cascade,
  notification_type text not null check (notification_type in ('PROPOSAL_RECEIVED', 'PROPOSAL_ACCEPTED', 'PROPOSAL_REJECTED', 'AGREEMENT_BREACHED', 'AGREEMENT_TERMINATED')),
  read_at timestamptz,
  dismissed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.trade_admin_reviews (
  id bigint generated by default as identity primary key,
  proposal_id uuid references public.trade_proposals(id) on delete set null,
  agreement_id uuid references public.trade_agreements(id) on delete set null,
  admin_subject text not null,
  admin_kind text not null,
  action text not null,
  note text,
  world_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.country_trade_restrictions (
  id bigint generated by default as identity primary key,
  country_key text not null,
  target_country_key text,
  reason text not null,
  starts_world_date date not null,
  ends_world_date date,
  created_at timestamptz not null default now(),
  check (target_country_key is null or target_country_key <> country_key)
);

create or replace function public.tlr_economy_readiness(p_country text)
returns text language sql stable as $$
  select case
    when e.country_key is null then 'UNCONFIGURED'
    when e.gdp is null and e.base_production_capacity is null and e.national_income is null then 'UNCONFIGURED'
    when e.gdp is not null and e.nominal_growth_rate is not null and e.inflation_rate is not null
      and e.unemployment_rate is not null and e.national_debt is not null and e.foreign_reserves is not null
      and e.national_income is not null and e.total_expenditure is not null
      and e.base_production_capacity is not null and e.domestic_capacity_used is not null
      and e.nominal_tax_rate is not null and e.tax_collection_efficiency is not null
      and jsonb_typeof(e.current_budget) = 'object'
      and e.current_budget ?& array['administration', 'defense', 'industry', 'welfare', 'education']
      and jsonb_typeof(e.current_budget -> 'administration') = 'number'
      and jsonb_typeof(e.current_budget -> 'defense') = 'number'
      and jsonb_typeof(e.current_budget -> 'industry') = 'number'
      and jsonb_typeof(e.current_budget -> 'welfare') = 'number'
      and jsonb_typeof(e.current_budget -> 'education') = 'number' then 'READY'
    else 'PARTIAL'
  end
  from (select p_country as country_key) c left join public.country_economies e using (country_key)
$$;

create or replace function public.tlr_trade_capacity_components(p_country text)
returns table(effective_capacity numeric, domestic_used numeric, committed_out numeric, received_in numeric, available numeric)
language sql stable as $$
  with base as (
    select e.base_production_capacity + coalesce(e.production_capacity_modifier, 0) effective,
      e.domestic_capacity_used domestic
    from public.country_economies e where e.country_key = p_country
  ), outgoing as (
    select coalesce(sum(l.amount_per_settlement), 0) value
    from public.trade_agreement_lines l join public.trade_agreements a on a.id = l.agreement_id
    where a.status in ('SCHEDULED', 'ACTIVE') and l.asset_type = 'PRODUCTION_CAPACITY' and l.from_country_key = p_country
  ), incoming as (
    select coalesce(sum(l.amount_per_settlement), 0) value
    from public.trade_agreement_lines l join public.trade_agreements a on a.id = l.agreement_id
    where a.status = 'ACTIVE' and l.asset_type = 'PRODUCTION_CAPACITY' and l.to_country_key = p_country
  )
  select b.effective, b.domestic, o.value, i.value,
    greatest(0, b.effective + i.value - b.domestic - o.value)
  from base b cross join outgoing o cross join incoming i
$$;

create or replace function public.tlr_trade_resource_components(p_country text, p_resource text)
returns table(stockpile numeric, production numeric, domestic_used numeric, committed_out numeric, received_in numeric, available numeric)
language sql stable as $$
  with base as (
    select r.stockpile, r.production_per_period, r.domestic_use, r.export_limit
    from public.country_resources r where r.country_key = p_country and r.resource_type_id = p_resource
  ), outgoing as (
    select coalesce(sum(l.amount_per_settlement), 0) value
    from public.trade_agreement_lines l join public.trade_agreements a on a.id = l.agreement_id
    where a.status in ('SCHEDULED', 'ACTIVE') and l.asset_type = 'RESOURCE' and l.resource_type_id = p_resource and l.from_country_key = p_country
  ), incoming as (
    select coalesce(sum(l.amount_per_settlement), 0) value
    from public.trade_agreement_lines l join public.trade_agreements a on a.id = l.agreement_id
    where a.status = 'ACTIVE' and l.asset_type = 'RESOURCE' and l.resource_type_id = p_resource and l.to_country_key = p_country
  )
  select b.stockpile, b.production_per_period, b.domestic_use, o.value, i.value,
    greatest(0, least(coalesce(b.export_limit, b.stockpile + b.production_per_period), b.stockpile + b.production_per_period + i.value - b.domestic_use - o.value))
  from base b cross join outgoing o cross join incoming i
$$;

create or replace function public.tlr_validate_trade_line(p_from text, p_asset text, p_resource text, p_amount numeric)
returns void language plpgsql as $$
declare v_available numeric;
begin
  if p_amount is null or p_amount <= 0 then raise exception 'INVALID_TRADE_AMOUNT'; end if;
  if p_asset = 'PRODUCTION_CAPACITY' then
    select available into v_available from public.tlr_trade_capacity_components(p_from);
    if v_available is null then raise exception 'PRODUCTION_CAPACITY_UNCONFIGURED'; end if;
  elsif p_asset = 'RESOURCE' and p_resource is not null then
    select available into v_available from public.tlr_trade_resource_components(p_from, p_resource);
    if v_available is null then raise exception 'RESOURCE_UNCONFIGURED'; end if;
  else raise exception 'INVALID_TRADE_ASSET';
  end if;
  if v_available < p_amount then raise exception 'TRADE_ASSET_INSUFFICIENT'; end if;
end $$;

create or replace function public.tlr_validate_committed_trade_asset(p_from text, p_asset text, p_resource text)
returns void language plpgsql as $$
declare v_supply numeric; v_committed numeric; v_export_limit numeric;
begin
  if p_asset = 'PRODUCTION_CAPACITY' then
    select effective_capacity + received_in - domestic_used, committed_out
      into v_supply, v_committed from public.tlr_trade_capacity_components(p_from);
  elsif p_asset = 'RESOURCE' and p_resource is not null then
    select stockpile + production + received_in - domestic_used, committed_out,
      (select export_limit from public.country_resources where country_key = p_from and resource_type_id = p_resource)
      into v_supply, v_committed, v_export_limit
      from public.tlr_trade_resource_components(p_from, p_resource);
    v_supply := least(coalesce(v_export_limit, v_supply), v_supply);
  else
    raise exception 'INVALID_TRADE_ASSET';
  end if;
  if v_supply is null then raise exception 'TRADE_ASSET_UNCONFIGURED'; end if;
  if v_supply < v_committed then raise exception 'TRADE_ASSET_INSUFFICIENT'; end if;
end $$;

create or replace function public.tlr_create_trade_proposal(
  p_proposer text, p_receiver text, p_review_route text, p_lines jsonb,
  p_start date, p_end date, p_interval integer, p_deadline date,
  p_auto_renew boolean, p_allow_early boolean, p_allow_partial boolean,
  p_idempotency_key text, p_world_date date
) returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_line jsonb; v_from text; v_to text; v_asset text; v_resource text; v_amount numeric;
begin
  if p_proposer = p_receiver then raise exception 'SELF_TRADE'; end if;
  if p_review_route not in ('PLAYER', 'ADMIN') then raise exception 'INVALID_REVIEW_ROUTE'; end if;
  if p_start < p_world_date or p_end <= p_start or p_deadline < p_world_date or p_deadline > p_start then raise exception 'INVALID_TRADE_DATES'; end if;
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) < 2 then raise exception 'TRADE_LINES_REQUIRED'; end if;
  perform 1 from public.country_economies where country_key in (p_proposer, p_receiver) for update;
  if not exists (select 1 from public.country_economies where country_key = p_proposer and base_production_capacity is not null and domestic_capacity_used is not null)
    or not exists (select 1 from public.country_economies where country_key = p_receiver and base_production_capacity is not null and domestic_capacity_used is not null)
  then raise exception 'ECONOMY_NOT_TRADE_READY'; end if;
  if exists (select 1 from public.country_trade_restrictions r where r.country_key = p_proposer and (r.target_country_key is null or r.target_country_key = p_receiver)
    and r.starts_world_date <= p_world_date and (r.ends_world_date is null or r.ends_world_date >= p_world_date)) then raise exception 'TRADE_RESTRICTED'; end if;
  insert into public.trade_proposals (proposer_country_key, receiver_country_key, review_route, proposed_start_world_date,
    proposed_end_world_date, settlement_interval_days, response_deadline_world_date, auto_renew,
    allow_early_termination, allow_partial_fulfillment, idempotency_key)
  values (p_proposer, p_receiver, p_review_route, p_start, p_end, p_interval, p_deadline, p_auto_renew, p_allow_early, p_allow_partial, p_idempotency_key)
  returning id into v_id;
  for v_line in select value from jsonb_array_elements(p_lines) loop
    v_from := v_line->>'fromCountryKey'; v_to := v_line->>'toCountryKey'; v_asset := v_line->>'assetType';
    v_resource := nullif(v_line->>'resourceTypeId', ''); v_amount := (v_line->>'amount')::numeric;
    if v_from not in (p_proposer, p_receiver) or v_to not in (p_proposer, p_receiver) or v_from = v_to then raise exception 'INVALID_TRADE_LINE_COUNTRY'; end if;
    insert into public.trade_proposal_lines (proposal_id, from_country_key, to_country_key, asset_type, resource_type_id, amount_per_settlement)
    values (v_id, v_from, v_to, v_asset, v_resource, v_amount);
  end loop;
  if not exists (select 1 from public.trade_proposal_lines where proposal_id = v_id and from_country_key = p_proposer)
    or not exists (select 1 from public.trade_proposal_lines where proposal_id = v_id and from_country_key = p_receiver)
  then raise exception 'BILATERAL_TRADE_REQUIRED'; end if;
  for v_from, v_asset, v_resource, v_amount in
    select from_country_key, asset_type, resource_type_id, sum(amount_per_settlement)
    from public.trade_proposal_lines where proposal_id = v_id
    group by from_country_key, asset_type, resource_type_id
  loop
    perform public.tlr_validate_trade_line(v_from, v_asset, v_resource, v_amount);
  end loop;
  insert into public.trade_history (country_key, related_country_key, proposal_id, action_type, world_date)
  values (p_proposer, p_receiver, v_id, 'PROPOSAL_CREATED', p_world_date);
  if p_review_route = 'PLAYER' then
    insert into public.trade_notifications (country_key, counterpart_country_key, proposal_id, notification_type)
    values (p_receiver, p_proposer, v_id, 'PROPOSAL_RECEIVED');
  end if;
  return v_id;
exception when unique_violation then
  if exists (select 1 from public.trade_proposals where idempotency_key = p_idempotency_key) then
    return (select id from public.trade_proposals where idempotency_key = p_idempotency_key);
  end if;
  raise exception 'DUPLICATE_PENDING_TRADE';
end $$;

create or replace function public.tlr_accept_trade_proposal(p_proposal_id uuid, p_receiver text, p_user_id uuid, p_world_date date)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_p public.trade_proposals%rowtype; v_l record; v_agreement uuid; v_status text;
begin
  select * into v_p from public.trade_proposals where id = p_proposal_id for update;
  if not found then raise exception 'TRADE_PROPOSAL_NOT_FOUND'; end if;
  if v_p.status <> 'PENDING' then raise exception 'TRADE_PROPOSAL_NOT_PENDING'; end if;
  if v_p.receiver_country_key <> p_receiver then raise exception 'NOT_TRADE_RECEIVER'; end if;
  if v_p.response_deadline_world_date < p_world_date then
    update public.trade_proposals set status = 'EXPIRED', updated_at = now() where id = p_proposal_id;
    raise exception 'TRADE_PROPOSAL_EXPIRED';
  end if;
  perform 1 from public.country_economies where country_key in (v_p.proposer_country_key, v_p.receiver_country_key) for update;
  for v_l in
    select from_country_key, asset_type, resource_type_id, sum(amount_per_settlement) amount_per_settlement
    from public.trade_proposal_lines where proposal_id = p_proposal_id
    group by from_country_key, asset_type, resource_type_id
  loop
    perform public.tlr_validate_trade_line(v_l.from_country_key, v_l.asset_type, v_l.resource_type_id, v_l.amount_per_settlement);
  end loop;
  v_status := case when v_p.proposed_start_world_date <= p_world_date then 'ACTIVE' else 'SCHEDULED' end;
  insert into public.trade_agreements (created_from_proposal_id, country_a_key, country_b_key, status, starts_world_date, ends_world_date,
    settlement_interval_days, next_settlement_world_date, auto_renew, allow_early_termination, allow_partial_fulfillment)
  values (v_p.id, v_p.proposer_country_key, v_p.receiver_country_key, v_status, v_p.proposed_start_world_date, v_p.proposed_end_world_date,
    v_p.settlement_interval_days, v_p.proposed_start_world_date, v_p.auto_renew, v_p.allow_early_termination, v_p.allow_partial_fulfillment)
  returning id into v_agreement;
  insert into public.trade_agreement_lines (agreement_id, from_country_key, to_country_key, asset_type, resource_type_id, amount_per_settlement)
  select v_agreement, from_country_key, to_country_key, asset_type, resource_type_id, amount_per_settlement
  from public.trade_proposal_lines where proposal_id = v_p.id;
  update public.trade_proposals set status = 'ACCEPTED', updated_at = now() where id = v_p.id and status = 'PENDING';
  insert into public.trade_history (actor_user_id, country_key, related_country_key, proposal_id, agreement_id, action_type, world_date)
  values (p_user_id, p_receiver, v_p.proposer_country_key, v_p.id, v_agreement, 'PROPOSAL_ACCEPTED', p_world_date);
  insert into public.trade_notifications (country_key, counterpart_country_key, proposal_id, agreement_id, notification_type)
  values (v_p.proposer_country_key, v_p.receiver_country_key, v_p.id, v_agreement, 'PROPOSAL_ACCEPTED');
  return v_agreement;
end $$;

create or replace function public.tlr_run_economy_period(p_country text, p_period_start date, p_period_end date)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_e public.country_economies%rowtype; v_status text; v_id bigint; v_key text;
begin
  if p_period_start > p_period_end then raise exception 'INVALID_ECONOMY_PERIOD'; end if;
  select * into v_e from public.country_economies where country_key = p_country for update;
  if not found then raise exception 'ECONOMY_UNCONFIGURED'; end if;
  v_key := p_country || ':' || p_period_start::text || ':' || p_period_end::text;
  v_status := case when public.tlr_economy_readiness(p_country) = 'READY' then 'APPLIED' else 'BLOCKED_MISSING_DATA' end;

  if v_status = 'APPLIED' and v_e.next_budget is not null and v_e.next_budget_world_date <= p_period_end then
    update public.country_economies
    set current_budget = next_budget, next_budget = null, next_budget_world_date = null, updated_at = now()
    where country_key = p_country;
  end if;

  insert into public.economy_history (country_key, period_start, period_end, status, snapshot, idempotency_key)
  values (p_country, p_period_start, p_period_end, v_status,
    jsonb_build_object('readiness', public.tlr_economy_readiness(p_country), 'economy', to_jsonb(v_e)), v_key)
  on conflict (idempotency_key) do update set idempotency_key = excluded.idempotency_key
  returning id into v_id;
  return v_id;
end $$;

create or replace function public.tlr_preview_economy_period(p_country text, p_period_start date, p_period_end date)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_e public.country_economies%rowtype; v_readiness text;
begin
  if p_period_start > p_period_end then raise exception 'INVALID_ECONOMY_PERIOD'; end if;
  select * into v_e from public.country_economies where country_key = p_country;
  if not found then raise exception 'ECONOMY_UNCONFIGURED'; end if;
  v_readiness := public.tlr_economy_readiness(p_country);
  return jsonb_build_object(
    'countryKey', p_country,
    'periodStart', p_period_start,
    'periodEnd', p_period_end,
    'status', case when v_readiness = 'READY' then 'PREVIEW' else 'BLOCKED_MISSING_DATA' end,
    'readiness', v_readiness,
    'economy', to_jsonb(v_e),
    'calculatedChanges', null
  );
end $$;

create or replace function public.tlr_respond_trade_proposal(p_proposal_id uuid, p_receiver text, p_response text, p_user_id uuid, p_world_date date)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_p public.trade_proposals%rowtype;
begin
  if p_response = 'ACCEPTED' then return public.tlr_accept_trade_proposal(p_proposal_id, p_receiver, p_user_id, p_world_date); end if;
  if p_response <> 'REJECTED' then raise exception 'INVALID_TRADE_RESPONSE'; end if;
  select * into v_p from public.trade_proposals where id = p_proposal_id for update;
  if not found then raise exception 'TRADE_PROPOSAL_NOT_FOUND'; end if;
  if v_p.status <> 'PENDING' then raise exception 'TRADE_PROPOSAL_NOT_PENDING'; end if;
  if v_p.receiver_country_key <> p_receiver then raise exception 'NOT_TRADE_RECEIVER'; end if;
  update public.trade_proposals set status = 'REJECTED', updated_at = now() where id = p_proposal_id;
  insert into public.trade_history (actor_user_id, country_key, related_country_key, proposal_id, action_type, world_date)
  values (p_user_id, p_receiver, v_p.proposer_country_key, v_p.id, 'PROPOSAL_REJECTED', p_world_date);
  insert into public.trade_notifications (country_key, counterpart_country_key, proposal_id, notification_type)
  values (v_p.proposer_country_key, v_p.receiver_country_key, v_p.id, 'PROPOSAL_REJECTED');
  return null;
end $$;

create or replace function public.tlr_withdraw_trade_proposal(p_proposal_id uuid, p_proposer text, p_user_id uuid, p_world_date date)
returns void language plpgsql security definer set search_path = public as $$
declare v_receiver text;
begin
  update public.trade_proposals set status = 'WITHDRAWN', updated_at = now()
  where id = p_proposal_id and proposer_country_key = p_proposer and status = 'PENDING'
  returning receiver_country_key into v_receiver;
  if v_receiver is null then raise exception 'TRADE_PROPOSAL_NOT_PENDING'; end if;
  insert into public.trade_history (actor_user_id, country_key, related_country_key, proposal_id, action_type, world_date)
  values (p_user_id, p_proposer, v_receiver, p_proposal_id, 'PROPOSAL_WITHDRAWN', p_world_date);
end $$;

create or replace function public.tlr_refresh_trade_state(p_world_date date)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.trade_proposals set status = 'EXPIRED', updated_at = now()
  where status = 'PENDING' and response_deadline_world_date < p_world_date;
  update public.trade_agreements set status = 'ACTIVE', updated_at = now()
  where status = 'SCHEDULED' and starts_world_date <= p_world_date and ends_world_date >= p_world_date;
  update public.trade_agreements set status = 'EXPIRED', next_settlement_world_date = null, updated_at = now()
  where status in ('SCHEDULED', 'ACTIVE', 'SUSPENDED') and ends_world_date < p_world_date;
end $$;

create or replace function public.tlr_settle_trade_agreement(p_agreement_id uuid, p_world_date date)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_a public.trade_agreements%rowtype; v_l record; v_id uuid; v_key text; v_existing_status text;
begin
  select * into v_a from public.trade_agreements where id = p_agreement_id for update;
  if not found then raise exception 'TRADE_AGREEMENT_NOT_FOUND'; end if;
  if v_a.status <> 'ACTIVE' then raise exception 'TRADE_AGREEMENT_NOT_ACTIVE'; end if;
  if v_a.next_settlement_world_date is null or v_a.next_settlement_world_date > p_world_date then raise exception 'TRADE_SETTLEMENT_NOT_DUE'; end if;
  v_key := v_a.id::text || ':' || v_a.next_settlement_world_date::text;
  insert into public.trade_settlements (agreement_id, scheduled_world_date, status, idempotency_key)
  values (v_a.id, v_a.next_settlement_world_date, 'PENDING', v_key)
  on conflict (idempotency_key) do nothing;
  select id, status into v_id, v_existing_status from public.trade_settlements where idempotency_key = v_key for update;
  if v_existing_status = 'COMPLETED' then return v_id; end if;
  for v_l in
    select from_country_key, asset_type, resource_type_id
    from public.trade_agreement_lines where agreement_id = v_a.id
    group by from_country_key, asset_type, resource_type_id
  loop
    begin
      perform public.tlr_validate_committed_trade_asset(v_l.from_country_key, v_l.asset_type, v_l.resource_type_id);
    exception when others then
      update public.trade_settlements set status = 'FAILED', executed_world_date = p_world_date,
        result = jsonb_build_object('code', 'ASSET_SHORTAGE', 'countryKey', v_l.from_country_key, 'assetType', v_l.asset_type,
          'resourceTypeId', v_l.resource_type_id) where id = v_id;
      update public.trade_agreements set status = 'BREACHED', updated_at = now() where id = v_a.id;
      insert into public.trade_notifications (country_key, counterpart_country_key, agreement_id, notification_type) values
        (v_a.country_a_key, v_a.country_b_key, v_a.id, 'AGREEMENT_BREACHED'),
        (v_a.country_b_key, v_a.country_a_key, v_a.id, 'AGREEMENT_BREACHED');
      return v_id;
    end;
  end loop;
  -- 초기 무역은 반복 공급 계약이다. 재고를 영구 이전하지 않고 ACTIVE 계약과
  -- 정산 원장으로 수입·수출 흐름을 계산하여 같은 생산량이 여러 번 적립되지 않게 한다.
  update public.trade_settlements set status = 'COMPLETED', executed_world_date = p_world_date,
    result = jsonb_build_object('lines', (select coalesce(jsonb_agg(jsonb_build_object('fromCountryKey', from_country_key, 'toCountryKey', to_country_key,
      'assetType', asset_type, 'resourceTypeId', resource_type_id, 'amount', amount_per_settlement)), '[]'::jsonb)
      from public.trade_agreement_lines where agreement_id = v_a.id)) where id = v_id;
  insert into public.trade_history (country_key, related_country_key, agreement_id, action_type, details, world_date)
  values (v_a.country_a_key, v_a.country_b_key, v_a.id, 'SETTLEMENT_COMPLETED',
    jsonb_build_object('scheduledWorldDate', v_a.next_settlement_world_date, 'settlementId', v_id), p_world_date);
  update public.trade_agreements set
    ends_world_date = case
      when auto_renew and next_settlement_world_date + settlement_interval_days > ends_world_date
        then ends_world_date + (ends_world_date - starts_world_date)
      else ends_world_date
    end,
    next_settlement_world_date = case
      when not auto_renew and next_settlement_world_date + settlement_interval_days > ends_world_date then null
      else next_settlement_world_date + settlement_interval_days
    end,
    status = case
      when not auto_renew and next_settlement_world_date + settlement_interval_days > ends_world_date then 'EXPIRED'
      else status
    end,
    updated_at = now() where id = v_a.id;
  return v_id;
end $$;

create or replace function public.tlr_refresh_trade_state(p_world_date date)
returns void language plpgsql security definer set search_path = public as $$
declare v_agreement_id uuid;
begin
  update public.trade_proposals set status = 'EXPIRED', updated_at = now()
  where status = 'PENDING' and response_deadline_world_date < p_world_date;
  update public.trade_agreements set status = 'ACTIVE', updated_at = now()
  where status = 'SCHEDULED' and starts_world_date <= p_world_date and ends_world_date >= p_world_date;
  update public.trade_agreements set status = 'EXPIRED', next_settlement_world_date = null, updated_at = now()
  where status in ('SCHEDULED', 'ACTIVE', 'SUSPENDED') and ends_world_date < p_world_date;
  loop
    select id into v_agreement_id from public.trade_agreements
    where status = 'ACTIVE' and next_settlement_world_date is not null and next_settlement_world_date <= p_world_date
    order by next_settlement_world_date, id limit 1;
    exit when not found;
    perform public.tlr_settle_trade_agreement(v_agreement_id, p_world_date);
  end loop;
end $$;

create or replace function public.tlr_terminate_trade_agreement(p_agreement_id uuid, p_country text, p_user_id uuid, p_world_date date)
returns void language plpgsql security definer set search_path = public as $$
declare v_a public.trade_agreements%rowtype; v_other text;
begin
  select * into v_a from public.trade_agreements where id = p_agreement_id for update;
  if not found then raise exception 'TRADE_AGREEMENT_NOT_FOUND'; end if;
  if p_country not in (v_a.country_a_key, v_a.country_b_key) then raise exception 'NOT_TRADE_PARTY'; end if;
  if v_a.status not in ('SCHEDULED', 'ACTIVE', 'SUSPENDED', 'BREACHED') then raise exception 'TRADE_AGREEMENT_CLOSED'; end if;
  if not v_a.allow_early_termination then raise exception 'EARLY_TERMINATION_NOT_ALLOWED'; end if;
  v_other := case when p_country = v_a.country_a_key then v_a.country_b_key else v_a.country_a_key end;
  update public.trade_agreements set status = 'TERMINATED', next_settlement_world_date = null, updated_at = now() where id = v_a.id;
  insert into public.trade_history (actor_user_id, country_key, related_country_key, agreement_id, action_type, world_date)
  values (p_user_id, p_country, v_other, v_a.id, 'AGREEMENT_TERMINATED', p_world_date);
  insert into public.trade_notifications (country_key, counterpart_country_key, agreement_id, notification_type)
  values (v_other, p_country, v_a.id, 'AGREEMENT_TERMINATED');
end $$;

create or replace function public.tlr_save_budget_draft(p_country text, p_budget jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare v_value jsonb; v_number numeric;
begin
  if jsonb_typeof(p_budget) <> 'object' then raise exception 'INVALID_BUDGET'; end if;
  for v_value in select value from jsonb_each(p_budget) loop
    if jsonb_typeof(v_value) <> 'number' then raise exception 'INVALID_BUDGET'; end if;
    v_number := (v_value #>> '{}')::numeric;
    if v_number < 0 or v_number > 100 or trunc(v_number) <> v_number then raise exception 'INVALID_BUDGET'; end if;
  end loop;
  update public.country_economies set draft_budget = p_budget, updated_at = now() where country_key = p_country;
  if not found then raise exception 'ECONOMY_UNCONFIGURED'; end if;
end $$;

create or replace function public.tlr_confirm_budget(p_country text, p_world_date date)
returns void language plpgsql security definer set search_path = public as $$
declare v_interval integer;
begin
  select settlement_interval_days into v_interval from public.economy_rules where singleton = true;
  update public.country_economies set next_budget = draft_budget, draft_budget = null,
    next_budget_world_date = p_world_date + coalesce(v_interval, 30), updated_at = now()
  where country_key = p_country and draft_budget is not null;
  if not found then raise exception 'BUDGET_DRAFT_REQUIRED'; end if;
end $$;

alter table public.economy_rules enable row level security;
alter table public.country_economies enable row level security;
alter table public.economy_resource_types enable row level security;
alter table public.country_resources enable row level security;
alter table public.economy_history enable row level security;
alter table public.trade_proposals enable row level security;
alter table public.trade_proposal_lines enable row level security;
alter table public.trade_agreements enable row level security;
alter table public.trade_agreement_lines enable row level security;
alter table public.trade_settlements enable row level security;
alter table public.trade_history enable row level security;
alter table public.trade_notifications enable row level security;
alter table public.trade_admin_reviews enable row level security;
alter table public.country_trade_restrictions enable row level security;

revoke all on public.economy_rules, public.country_economies, public.economy_resource_types, public.country_resources,
  public.economy_history, public.trade_proposals, public.trade_proposal_lines, public.trade_agreements,
  public.trade_agreement_lines, public.trade_settlements, public.trade_history, public.trade_notifications,
  public.trade_admin_reviews, public.country_trade_restrictions from anon, authenticated;
revoke all on function public.tlr_create_trade_proposal(text, text, text, jsonb, date, date, integer, date, boolean, boolean, boolean, text, date) from anon, authenticated;
revoke all on function public.tlr_accept_trade_proposal(uuid, text, uuid, date) from anon, authenticated;
revoke all on function public.tlr_respond_trade_proposal(uuid, text, text, uuid, date) from anon, authenticated;
revoke all on function public.tlr_withdraw_trade_proposal(uuid, text, uuid, date) from anon, authenticated;
revoke all on function public.tlr_settle_trade_agreement(uuid, date) from anon, authenticated;
revoke all on function public.tlr_refresh_trade_state(date) from anon, authenticated;
revoke all on function public.tlr_run_economy_period(text, date, date) from anon, authenticated;
revoke all on function public.tlr_preview_economy_period(text, date, date) from anon, authenticated;
revoke all on function public.tlr_terminate_trade_agreement(uuid, text, uuid, date) from anon, authenticated;
revoke all on function public.tlr_save_budget_draft(text, jsonb) from anon, authenticated;
revoke all on function public.tlr_confirm_budget(text, date) from anon, authenticated;
