create table if not exists public.world_state (
  singleton boolean primary key default true check (singleton),
  current_world_date date not null default date '1932-04-03',
  updated_at timestamptz not null default now()
);

insert into public.world_state (singleton, current_world_date)
values (true, date '1932-04-03')
on conflict (singleton) do nothing;

create table if not exists public.country_ownerships (
  country_key text primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'revoked')),
  assigned_at timestamptz not null default now(),
  revoked_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists country_ownerships_one_active_country_per_user
  on public.country_ownerships(user_id) where status = 'active';

create table if not exists public.country_access_restrictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  country_key text not null,
  reason text not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.country_relations (
  source_country_key text not null,
  target_country_key text not null,
  base_score integer not null default 0 check (base_score between -100 and 100),
  updated_at timestamptz not null default now(),
  primary key (source_country_key, target_country_key),
  check (source_country_key <> target_country_key)
);

create table if not exists public.country_relation_modifiers (
  id bigint generated by default as identity primary key,
  source_country_key text not null,
  target_country_key text not null,
  modifier_type text not null,
  value integer not null,
  title text not null,
  starts_world_date date,
  ends_world_date date,
  source_reference text,
  created_at timestamptz not null default now(),
  check (source_country_key <> target_country_key)
);

create table if not exists public.country_relation_history (
  id bigint generated by default as identity primary key,
  source_country_key text not null,
  target_country_key text not null,
  previous_score integer not null,
  change_amount integer not null,
  next_score integer not null,
  reason text not null,
  source_type text not null check (source_type in ('DIPLOMATIC_ACTION', 'TREATY', 'EVENT', 'DECISION', 'NATIONAL_SPIRIT', 'ADMIN')),
  source_reference text,
  world_date date not null,
  created_at timestamptz not null default now(),
  check (source_country_key <> target_country_key),
  check (previous_score between -100 and 100),
  check (next_score between -100 and 100)
);

create table if not exists public.diplomatic_proposals (
  id uuid primary key default gen_random_uuid(),
  proposer_country_key text not null,
  receiver_country_key text not null,
  proposal_type text not null check (proposal_type in ('NON_AGGRESSION', 'TRADE_AGREEMENT', 'FACTION_INVITATION', 'MILITARY_ACCESS', 'INDEPENDENCE_GUARANTEE')),
  status text not null default 'PENDING' check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'CANCELLED')),
  review_route text not null check (review_route in ('PLAYER', 'ADMIN')),
  terms jsonb not null default '{}'::jsonb,
  proposed_start_world_date date not null,
  proposed_end_world_date date,
  response_deadline_world_date date not null,
  sent_world_date date not null,
  responded_world_date date,
  responded_by_user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (proposer_country_key <> receiver_country_key),
  check (proposed_end_world_date is null or proposed_end_world_date >= proposed_start_world_date),
  check (response_deadline_world_date >= sent_world_date)
);

create unique index if not exists diplomatic_proposals_unique_pending
  on public.diplomatic_proposals (
    least(proposer_country_key, receiver_country_key),
    greatest(proposer_country_key, receiver_country_key),
    proposal_type
  ) where status = 'PENDING';

create table if not exists public.diplomatic_agreements (
  id uuid primary key default gen_random_uuid(),
  country_a_key text not null,
  country_b_key text not null,
  agreement_type text not null check (agreement_type in ('NON_AGGRESSION', 'TRADE_AGREEMENT', 'FACTION_MEMBERSHIP', 'MILITARY_ACCESS', 'INDEPENDENCE_GUARANTEE')),
  status text not null check (status in ('SCHEDULED', 'ACTIVE', 'EXPIRED', 'TERMINATED', 'CANCELLED')),
  starts_world_date date not null,
  ends_world_date date,
  terms jsonb not null default '{}'::jsonb,
  created_from_proposal_id uuid unique references public.diplomatic_proposals(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (country_a_key < country_b_key),
  check (ends_world_date is null or ends_world_date >= starts_world_date)
);

create unique index if not exists diplomatic_agreements_unique_live
  on public.diplomatic_agreements(country_a_key, country_b_key, agreement_type)
  where status in ('SCHEDULED', 'ACTIVE');

create table if not exists public.diplomacy_events (
  id bigint generated by default as identity primary key,
  actor_country_key text,
  counterpart_country_key text,
  event_type text not null,
  proposal_id uuid references public.diplomatic_proposals(id) on delete set null,
  agreement_id uuid references public.diplomatic_agreements(id) on delete set null,
  detail jsonb not null default '{}'::jsonb,
  world_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.diplomacy_notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_country_key text not null,
  counterpart_country_key text,
  notification_type text not null check (notification_type in ('PROPOSAL_RECEIVED', 'PROPOSAL_ACCEPTED', 'PROPOSAL_REJECTED', 'PROPOSAL_WITHDRAWN', 'PROPOSAL_EXPIRED', 'AGREEMENT_CREATED', 'AGREEMENT_ENDED', 'ADMIN_CANCELLED')),
  proposal_id uuid references public.diplomatic_proposals(id) on delete cascade,
  agreement_id uuid references public.diplomatic_agreements(id) on delete cascade,
  read_at timestamptz,
  dismissed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.diplomatic_action_cooldowns (
  country_key text not null,
  target_country_key text not null,
  action_type text not null,
  available_world_date date not null,
  primary key (country_key, target_country_key, action_type),
  check (country_key <> target_country_key)
);

create table if not exists public.diplomacy_admin_reviews (
  id bigint generated by default as identity primary key,
  proposal_id uuid not null references public.diplomatic_proposals(id) on delete cascade,
  admin_subject text not null,
  admin_kind text not null check (admin_kind in ('bootstrap', 'discord')),
  proposer_country_key text not null,
  receiver_country_key text not null,
  decision text not null check (decision in ('ACCEPTED', 'REJECTED', 'CANCELLED')),
  world_date date not null,
  created_at timestamptz not null default now()
);

create or replace function public.tlr_relation_total(
  p_source text,
  p_target text,
  p_world_date date
) returns integer
language sql stable
as $$
  select greatest(-100, least(100,
    r.base_score + coalesce(sum(m.value) filter (
      where (m.starts_world_date is null or m.starts_world_date <= p_world_date)
        and (m.ends_world_date is null or m.ends_world_date >= p_world_date)
    ), 0)
  ))::integer
  from public.country_relations r
  left join public.country_relation_modifiers m
    on m.source_country_key = r.source_country_key
   and m.target_country_key = r.target_country_key
  where r.source_country_key = p_source and r.target_country_key = p_target
  group by r.base_score;
$$;

create or replace function public.tlr_change_relation(
  p_source text,
  p_target text,
  p_amount integer,
  p_reason text,
  p_source_type text,
  p_source_reference text,
  p_world_date date
) returns integer
language plpgsql
as $$
declare
  v_previous integer;
  v_next integer;
begin
  if p_source = p_target then raise exception 'SELF_RELATION'; end if;
  insert into public.country_relations(source_country_key, target_country_key, base_score)
  values (p_source, p_target, 0)
  on conflict (source_country_key, target_country_key) do nothing;
  select base_score into v_previous from public.country_relations
    where source_country_key = p_source and target_country_key = p_target for update;
  v_next := greatest(-100, least(100, v_previous + p_amount));
  update public.country_relations set base_score = v_next, updated_at = now()
    where source_country_key = p_source and target_country_key = p_target;
  insert into public.country_relation_history(
    source_country_key, target_country_key, previous_score, change_amount,
    next_score, reason, source_type, source_reference, world_date
  ) values (
    p_source, p_target, v_previous, v_next - v_previous,
    v_next, p_reason, p_source_type, p_source_reference, p_world_date
  );
  return v_next;
end;
$$;

create or replace function public.tlr_expire_diplomacy(p_world_date date)
returns void language plpgsql as $$
declare v_row record;
begin
  for v_row in
    update public.diplomatic_proposals
      set status = 'EXPIRED', updated_at = now()
      where status = 'PENDING' and response_deadline_world_date < p_world_date
      returning *
  loop
    insert into public.diplomacy_events(actor_country_key, counterpart_country_key, event_type, proposal_id, world_date)
      values (v_row.proposer_country_key, v_row.receiver_country_key, 'PROPOSAL_EXPIRED', v_row.id, p_world_date);
    insert into public.diplomacy_notifications(recipient_country_key, counterpart_country_key, notification_type, proposal_id)
      values
        (v_row.proposer_country_key, v_row.receiver_country_key, 'PROPOSAL_EXPIRED', v_row.id),
        (v_row.receiver_country_key, v_row.proposer_country_key, 'PROPOSAL_EXPIRED', v_row.id);
  end loop;
  update public.diplomatic_agreements set status = 'ACTIVE', updated_at = now()
    where status = 'SCHEDULED' and starts_world_date <= p_world_date;
  update public.diplomatic_agreements set status = 'EXPIRED', updated_at = now()
    where status in ('SCHEDULED', 'ACTIVE') and ends_world_date is not null and ends_world_date < p_world_date;
end;
$$;

create or replace function public.tlr_apply_diplomatic_action(
  p_source text,
  p_target text,
  p_action_type text,
  p_world_date date
) returns integer language plpgsql as $$
declare v_amount integer; v_next integer; v_available date;
begin
  if p_source = p_target then raise exception 'SELF_TARGET'; end if;
  if p_action_type = 'IMPROVE_RELATIONS' then v_amount := 5;
  elsif p_action_type = 'WORSEN_RELATIONS' then v_amount := -5;
  else raise exception 'UNKNOWN_ACTION'; end if;
  select available_world_date into v_available from public.diplomatic_action_cooldowns
    where country_key = p_source and target_country_key = p_target and action_type = p_action_type for update;
  if v_available is not null and v_available > p_world_date then raise exception 'ACTION_COOLDOWN'; end if;
  v_next := public.tlr_change_relation(p_source, p_target, v_amount,
    case when v_amount > 0 then '관계 개선' else '관계 악화' end,
    'DIPLOMATIC_ACTION', p_action_type, p_world_date);
  insert into public.diplomatic_action_cooldowns(country_key, target_country_key, action_type, available_world_date)
    values (p_source, p_target, p_action_type, p_world_date + 7)
    on conflict (country_key, target_country_key, action_type)
    do update set available_world_date = excluded.available_world_date;
  insert into public.diplomacy_events(actor_country_key, counterpart_country_key, event_type, detail, world_date)
    values (p_source, p_target, p_action_type, jsonb_build_object('amount', v_amount), p_world_date);
  return v_next;
end;
$$;

create or replace function public.tlr_create_diplomatic_proposal(
  p_proposer text,
  p_receiver text,
  p_type text,
  p_review_route text,
  p_terms jsonb,
  p_start date,
  p_end date,
  p_deadline date,
  p_world_date date
) returns uuid language plpgsql as $$
declare v_id uuid;
begin
  if p_proposer = p_receiver then raise exception 'SELF_TARGET'; end if;
  if p_deadline < p_world_date then raise exception 'INVALID_DEADLINE'; end if;
  if p_start < p_world_date then raise exception 'INVALID_START_DATE'; end if;
  if p_end is not null and p_end < p_start then raise exception 'INVALID_END_DATE'; end if;
  if exists (
    select 1 from public.diplomatic_agreements
    where country_a_key = least(p_proposer, p_receiver)
      and country_b_key = greatest(p_proposer, p_receiver)
      and agreement_type = case p_type
        when 'NON_AGGRESSION' then 'NON_AGGRESSION'
        when 'TRADE_AGREEMENT' then 'TRADE_AGREEMENT'
        when 'FACTION_INVITATION' then 'FACTION_MEMBERSHIP'
        when 'MILITARY_ACCESS' then 'MILITARY_ACCESS'
        else 'INDEPENDENCE_GUARANTEE' end
      and status in ('SCHEDULED', 'ACTIVE')
  ) then raise exception 'AGREEMENT_EXISTS'; end if;
  insert into public.diplomatic_proposals(
    proposer_country_key, receiver_country_key, proposal_type, review_route,
    terms, proposed_start_world_date, proposed_end_world_date,
    response_deadline_world_date, sent_world_date
  ) values (
    p_proposer, p_receiver, p_type, p_review_route, coalesce(p_terms, '{}'::jsonb),
    p_start, p_end, p_deadline, p_world_date
  ) returning id into v_id;
  insert into public.diplomacy_events(actor_country_key, counterpart_country_key, event_type, proposal_id, world_date)
    values (p_proposer, p_receiver, 'PROPOSAL_SENT', v_id, p_world_date);
  if p_review_route = 'PLAYER' then
    insert into public.diplomacy_notifications(recipient_country_key, counterpart_country_key, notification_type, proposal_id)
      values (p_receiver, p_proposer, 'PROPOSAL_RECEIVED', v_id);
  end if;
  return v_id;
exception when unique_violation then
  raise exception 'DUPLICATE_PENDING_PROPOSAL';
end;
$$;

create or replace function public.tlr_respond_diplomatic_proposal(
  p_proposal_id uuid,
  p_receiver text,
  p_response text,
  p_user_id uuid,
  p_world_date date
) returns uuid language plpgsql as $$
declare v_row public.diplomatic_proposals%rowtype; v_agreement_id uuid; v_agreement_type text;
begin
  select * into v_row from public.diplomatic_proposals where id = p_proposal_id for update;
  if not found then raise exception 'PROPOSAL_NOT_FOUND'; end if;
  if v_row.status <> 'PENDING' then raise exception 'PROPOSAL_NOT_PENDING'; end if;
  if v_row.receiver_country_key <> p_receiver then raise exception 'NOT_PROPOSAL_RECEIVER'; end if;
  if v_row.response_deadline_world_date < p_world_date then
    update public.diplomatic_proposals set status = 'EXPIRED', updated_at = now() where id = p_proposal_id;
    raise exception 'PROPOSAL_EXPIRED';
  end if;
  if p_response not in ('ACCEPTED', 'REJECTED') then raise exception 'INVALID_RESPONSE'; end if;
  update public.diplomatic_proposals set status = p_response, responded_world_date = p_world_date,
    responded_by_user_id = p_user_id, updated_at = now() where id = p_proposal_id;
  insert into public.diplomacy_events(actor_country_key, counterpart_country_key, event_type, proposal_id, world_date)
    values (p_receiver, v_row.proposer_country_key, 'PROPOSAL_' || p_response, p_proposal_id, p_world_date);
  insert into public.diplomacy_notifications(recipient_country_key, counterpart_country_key, notification_type, proposal_id)
    values (v_row.proposer_country_key, p_receiver,
      case when p_response = 'ACCEPTED' then 'PROPOSAL_ACCEPTED' else 'PROPOSAL_REJECTED' end,
      p_proposal_id);
  if p_response = 'REJECTED' then return null; end if;
  v_agreement_type := case v_row.proposal_type
    when 'NON_AGGRESSION' then 'NON_AGGRESSION'
    when 'TRADE_AGREEMENT' then 'TRADE_AGREEMENT'
    when 'FACTION_INVITATION' then 'FACTION_MEMBERSHIP'
    when 'MILITARY_ACCESS' then 'MILITARY_ACCESS'
    else 'INDEPENDENCE_GUARANTEE' end;
  insert into public.diplomatic_agreements(
    country_a_key, country_b_key, agreement_type, status, starts_world_date,
    ends_world_date, terms, created_from_proposal_id
  ) values (
    least(v_row.proposer_country_key, v_row.receiver_country_key),
    greatest(v_row.proposer_country_key, v_row.receiver_country_key),
    v_agreement_type,
    case when v_row.proposed_start_world_date <= p_world_date then 'ACTIVE' else 'SCHEDULED' end,
    v_row.proposed_start_world_date, v_row.proposed_end_world_date, v_row.terms, v_row.id
  ) returning id into v_agreement_id;
  perform public.tlr_change_relation(v_row.proposer_country_key, v_row.receiver_country_key,
    case when v_row.proposal_type = 'TRADE_AGREEMENT' then 10 else 5 end,
    '외교 제안 수락', 'TREATY', v_agreement_id::text, p_world_date);
  perform public.tlr_change_relation(v_row.receiver_country_key, v_row.proposer_country_key,
    case when v_row.proposal_type = 'TRADE_AGREEMENT' then 7 else 5 end,
    '외교 제안 수락', 'TREATY', v_agreement_id::text, p_world_date);
  insert into public.diplomacy_events(actor_country_key, counterpart_country_key, event_type, proposal_id, agreement_id, world_date)
    values (v_row.proposer_country_key, v_row.receiver_country_key, 'AGREEMENT_CREATED', v_row.id, v_agreement_id, p_world_date);
  insert into public.diplomacy_notifications(recipient_country_key, counterpart_country_key, notification_type, proposal_id, agreement_id)
    values
      (v_row.proposer_country_key, v_row.receiver_country_key, 'AGREEMENT_CREATED', v_row.id, v_agreement_id),
      (v_row.receiver_country_key, v_row.proposer_country_key, 'AGREEMENT_CREATED', v_row.id, v_agreement_id);
  return v_agreement_id;
end;
$$;

create or replace function public.tlr_withdraw_diplomatic_proposal(
  p_proposal_id uuid,
  p_proposer text,
  p_world_date date
) returns void language plpgsql as $$
declare v_row public.diplomatic_proposals%rowtype;
begin
  select * into v_row from public.diplomatic_proposals where id = p_proposal_id for update;
  if not found then raise exception 'PROPOSAL_NOT_FOUND'; end if;
  if v_row.proposer_country_key <> p_proposer then raise exception 'NOT_PROPOSAL_PROPOSER'; end if;
  if v_row.status <> 'PENDING' then raise exception 'PROPOSAL_NOT_PENDING'; end if;
  update public.diplomatic_proposals set status = 'WITHDRAWN', updated_at = now() where id = p_proposal_id;
  update public.diplomacy_notifications set dismissed_at = now()
    where proposal_id = p_proposal_id and notification_type = 'PROPOSAL_RECEIVED';
  insert into public.diplomacy_events(actor_country_key, counterpart_country_key, event_type, proposal_id, world_date)
    values (p_proposer, v_row.receiver_country_key, 'PROPOSAL_WITHDRAWN', p_proposal_id, p_world_date);
  insert into public.diplomacy_notifications(recipient_country_key, counterpart_country_key, notification_type, proposal_id)
    values (v_row.receiver_country_key, p_proposer, 'PROPOSAL_WITHDRAWN', p_proposal_id);
end;
$$;

create or replace function public.tlr_admin_respond_diplomatic_proposal(
  p_proposal_id uuid,
  p_response text,
  p_world_date date,
  p_admin_subject text,
  p_admin_kind text
) returns uuid language plpgsql as $$
declare
  v_proposal public.diplomatic_proposals%rowtype;
  v_agreement_id uuid;
begin
  select * into v_proposal
    from public.diplomatic_proposals
    where id = p_proposal_id and review_route = 'ADMIN'
    for update;
  if not found then raise exception 'ADMIN_REVIEW_NOT_FOUND'; end if;
  v_agreement_id := public.tlr_respond_diplomatic_proposal(
    p_proposal_id,
    v_proposal.receiver_country_key,
    p_response,
    null,
    p_world_date
  );
  insert into public.diplomacy_admin_reviews(
    proposal_id, admin_subject, admin_kind, proposer_country_key,
    receiver_country_key, decision, world_date
  ) values (
    p_proposal_id, p_admin_subject, p_admin_kind, v_proposal.proposer_country_key,
    v_proposal.receiver_country_key, p_response, p_world_date
  );
  return v_agreement_id;
end;
$$;

create or replace function public.tlr_admin_cancel_diplomatic_proposal(
  p_proposal_id uuid,
  p_world_date date,
  p_admin_subject text,
  p_admin_kind text
) returns void language plpgsql as $$
declare v_proposal public.diplomatic_proposals%rowtype;
begin
  select * into v_proposal
    from public.diplomatic_proposals
    where id = p_proposal_id and review_route = 'ADMIN'
    for update;
  if not found then raise exception 'ADMIN_REVIEW_NOT_FOUND'; end if;
  if v_proposal.status <> 'PENDING' then raise exception 'PROPOSAL_NOT_PENDING'; end if;

  update public.diplomatic_proposals
    set status = 'CANCELLED', updated_at = now()
    where id = p_proposal_id;
  update public.diplomacy_notifications
    set dismissed_at = now()
    where proposal_id = p_proposal_id and notification_type = 'PROPOSAL_RECEIVED';
  insert into public.diplomacy_events(
    actor_country_key, counterpart_country_key, event_type, proposal_id, world_date
  ) values (
    v_proposal.receiver_country_key, v_proposal.proposer_country_key,
    'PROPOSAL_CANCELLED_BY_ADMIN', p_proposal_id, p_world_date
  );
  insert into public.diplomacy_notifications(
    recipient_country_key, counterpart_country_key, notification_type, proposal_id
  ) values (
    v_proposal.proposer_country_key, v_proposal.receiver_country_key,
    'ADMIN_CANCELLED', p_proposal_id
  );
  insert into public.diplomacy_admin_reviews(
    proposal_id, admin_subject, admin_kind, proposer_country_key,
    receiver_country_key, decision, world_date
  ) values (
    p_proposal_id, p_admin_subject, p_admin_kind, v_proposal.proposer_country_key,
    v_proposal.receiver_country_key, 'CANCELLED', p_world_date
  );
end;
$$;

-- Stable starting values. Relations are directional by design.
insert into public.country_relations(source_country_key, target_country_key, base_score)
values
  ('country-013', 'country-008', 36),
  ('country-008', 'country-013', 22),
  ('country-013', 'country-017', 28),
  ('country-017', 'country-013', 34),
  ('country-008', 'country-017', -18),
  ('country-017', 'country-008', -32)
on conflict (source_country_key, target_country_key) do nothing;

insert into public.country_relation_modifiers(
  source_country_key,
  target_country_key,
  modifier_type,
  value,
  title,
  starts_world_date,
  source_reference
)
select * from (values
  ('country-013', 'country-008', 'FACTION', 12, '유럽인민연방 공동 회원국', date '1932-01-01', 'european_peoples_federation'),
  ('country-008', 'country-013', 'IDEOLOGY', 8, '혁명권 연대', date '1932-01-01', 'revolutionary_solidarity'),
  ('country-008', 'country-017', 'CLAIM', -20, '미완의 독일 통일', date '1932-01-01', 'unfinished_german_unification'),
  ('country-017', 'country-008', 'SOVEREIGNTY', -16, '베를린의 그림자', date '1932-01-01', 'shadow_of_berlin')
) as seed(source_country_key, target_country_key, modifier_type, value, title, starts_world_date, source_reference)
where not exists (
  select 1 from public.country_relation_modifiers existing
  where existing.source_country_key = seed.source_country_key
    and existing.target_country_key = seed.target_country_key
    and existing.source_reference = seed.source_reference
);

alter table public.world_state enable row level security;
alter table public.country_ownerships enable row level security;
alter table public.country_access_restrictions enable row level security;
alter table public.country_relations enable row level security;
alter table public.country_relation_modifiers enable row level security;
alter table public.country_relation_history enable row level security;
alter table public.diplomatic_proposals enable row level security;
alter table public.diplomatic_agreements enable row level security;
alter table public.diplomacy_events enable row level security;
alter table public.diplomacy_notifications enable row level security;
alter table public.diplomatic_action_cooldowns enable row level security;
alter table public.diplomacy_admin_reviews enable row level security;

revoke all on public.world_state from anon, authenticated;
revoke all on public.country_ownerships from anon, authenticated;
revoke all on public.country_access_restrictions from anon, authenticated;
revoke all on public.country_relations from anon, authenticated;
revoke all on public.country_relation_modifiers from anon, authenticated;
revoke all on public.country_relation_history from anon, authenticated;
revoke all on public.diplomatic_proposals from anon, authenticated;
revoke all on public.diplomatic_agreements from anon, authenticated;
revoke all on public.diplomacy_events from anon, authenticated;
revoke all on public.diplomacy_notifications from anon, authenticated;
revoke all on public.diplomatic_action_cooldowns from anon, authenticated;
revoke all on public.diplomacy_admin_reviews from anon, authenticated;

revoke execute on function public.tlr_relation_total(text, text, date) from public, anon, authenticated;
revoke execute on function public.tlr_change_relation(text, text, integer, text, text, text, date) from public, anon, authenticated;
revoke execute on function public.tlr_expire_diplomacy(date) from public, anon, authenticated;
revoke execute on function public.tlr_apply_diplomatic_action(text, text, text, date) from public, anon, authenticated;
revoke execute on function public.tlr_create_diplomatic_proposal(text, text, text, text, jsonb, date, date, date) from public, anon, authenticated;
revoke execute on function public.tlr_respond_diplomatic_proposal(uuid, text, text, uuid, date) from public, anon, authenticated;
revoke execute on function public.tlr_withdraw_diplomatic_proposal(uuid, text, date) from public, anon, authenticated;
revoke execute on function public.tlr_admin_respond_diplomatic_proposal(uuid, text, date, text, text) from public, anon, authenticated;
revoke execute on function public.tlr_admin_cancel_diplomatic_proposal(uuid, date, text, text) from public, anon, authenticated;
