begin;

alter table public.world_state
  add column if not exists current_turn_id bigint;

create table if not exists public.turn_definitions (
  id bigint generated by default as identity primary key,
  turn_number integer not null unique check (turn_number > 0),
  start_world_date date not null,
  end_world_date date,
  status text not null default 'PLANNED' check (status in ('PLANNED','ACTIVE','SETTLED')),
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_world_date is null or end_world_date >= start_world_date)
);

insert into public.turn_definitions (turn_number,start_world_date,end_world_date,status)
select 1,current_world_date,null,'ACTIVE'
from public.world_state where singleton=true
on conflict (turn_number) do nothing;

update public.world_state
set current_turn_id = (select id from public.turn_definitions where status='ACTIVE' order by turn_number limit 1)
where singleton=true and current_turn_id is null;

alter table public.world_state
  add constraint world_state_current_turn_fk foreign key (current_turn_id) references public.turn_definitions(id);

create table if not exists public.turn_settlements (
  id bigint generated by default as identity primary key,
  turn_id bigint not null references public.turn_definitions(id),
  settlement_type text not null,
  status text not null check (status in ('PENDING','COMPLETED','FAILED')),
  world_date date not null,
  details jsonb not null default '{}'::jsonb,
  idempotency_key text not null unique,
  settled_by text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.world_time_advances (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  actor text not null,
  from_world_date date not null,
  target_world_date date not null,
  status text not null check (status in ('PENDING','COMPLETED','FAILED')),
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.turn_definitions enable row level security;
alter table public.turn_settlements enable row level security;
alter table public.world_time_advances enable row level security;
revoke all on public.turn_definitions,public.turn_settlements from anon,authenticated;
grant all on public.turn_definitions,public.turn_settlements to service_role;
revoke all on public.world_time_advances from anon,authenticated;
grant all on public.world_time_advances to service_role;

drop function if exists public.tlr_advance_country_stats(date);

-- 세계날짜를 읽거나 바꾸는 함수에서 호출하지 않는다. 턴 경계 처리기가 명시적으로 호출한다.
create or replace function public.tlr_settle_country_stats_turn(p_turn_id bigint,p_world_date date,p_actor text default 'system')
returns void language plpgsql security definer set search_path=public as $$
declare v_turn_number integer; v_key text;
begin
  select turn_number into v_turn_number from turn_definitions where id=p_turn_id for update;
  if v_turn_number is null then raise exception 'TURN_NOT_FOUND'; end if;
  v_key := p_turn_id::text || ':COUNTRY_STATS';
  insert into turn_settlements(turn_id,settlement_type,status,world_date,idempotency_key,settled_by)
  values(p_turn_id,'COUNTRY_STATS','PENDING',p_world_date,v_key,p_actor)
  on conflict(idempotency_key) do nothing;
  if not found then return; end if;
  update country_decision_states set
    political_power=greatest(0,coalesce(political_power,base_political_power,0)+coalesce(political_power_per_turn,0)*greatest(0,1+coalesce(political_power_gain_modifier,0)/100)),
    last_political_power_turn=v_turn_number,updated_at=now();
  update turn_settlements set status='COMPLETED',completed_at=now() where idempotency_key=v_key;
exception when others then
  update turn_settlements set status='FAILED',details=jsonb_build_object('error',sqlerrm) where idempotency_key=v_key;
  raise;
end; $$;

revoke execute on function public.tlr_settle_country_stats_turn(bigint,date,text) from public,anon,authenticated;
grant execute on function public.tlr_settle_country_stats_turn(bigint,date,text) to service_role;

create or replace function public.tlr_advance_world_time(p_target_date date,p_actor text,p_reason text,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_current_date date;
  v_current_turn bigint;
  v_boundary turn_definitions%rowtype;
  v_next turn_definitions%rowtype;
  v_crossed integer := 0;
  v_result jsonb;
  v_existing world_time_advances%rowtype;
begin
  select * into v_existing from world_time_advances where idempotency_key=p_idempotency_key;
  if found then return v_existing.result; end if;
  select current_world_date,current_turn_id into v_current_date,v_current_turn from world_state where singleton=true for update;
  if p_target_date <= v_current_date then raise exception 'WORLD_DATE_MUST_ADVANCE'; end if;
  if nullif(trim(p_reason),'') is null then raise exception 'WORLD_TIME_REASON_REQUIRED'; end if;
  insert into world_time_advances(idempotency_key,actor,from_world_date,target_world_date,status)
  values(p_idempotency_key,p_actor,v_current_date,p_target_date,'PENDING');

  for v_boundary in
    select * from turn_definitions
    where end_world_date is not null and end_world_date >= v_current_date and end_world_date <= p_target_date
    order by end_world_date,turn_number
  loop
    if v_boundary.id <> v_current_turn then raise exception 'TURN_SCHEDULE_GAP'; end if;
    select * into v_next from turn_definitions where turn_number=v_boundary.turn_number+1;
    if not found then raise exception 'NEXT_TURN_NOT_CONFIGURED'; end if;
    perform tlr_settle_country_stats_turn(v_boundary.id,v_boundary.end_world_date,p_actor);
    update turn_definitions set status='SETTLED',settled_at=now(),updated_at=now() where id=v_boundary.id;
    update turn_definitions set status='ACTIVE',updated_at=now() where id=v_next.id;
    update world_state set current_turn_id=v_next.id,updated_at=now() where singleton=true;
    v_current_turn := v_next.id;
    v_crossed := v_crossed+1;
  end loop;

  perform tlr_expire_diplomacy(p_target_date);
  perform tlr_advance_intelligence(p_target_date);
  perform tlr_refresh_trade_state(p_target_date);
  perform tlr_advance_research(p_target_date);
  update world_state set current_world_date=p_target_date,updated_at=now() where singleton=true;
  insert into world_control_audit_logs(actor,actor_kind,action,world_date,before_state,after_state,reason)
  values(p_actor,'ADMIN','WORLD_TIME_ADVANCED',p_target_date,jsonb_build_object('worldDate',v_current_date),jsonb_build_object('worldDate',p_target_date,'turnBoundaries',v_crossed),p_reason);
  v_result := jsonb_build_object('ok',true,'fromWorldDate',v_current_date,'targetWorldDate',p_target_date,'crossedTurnBoundaries',v_crossed,'currentTurnId',v_current_turn);
  update world_time_advances set status='COMPLETED',result=v_result,completed_at=now() where idempotency_key=p_idempotency_key;
  return v_result;
exception when others then
  v_result := jsonb_build_object('ok',false,'error',sqlerrm);
  return v_result;
end; $$;

revoke execute on function public.tlr_advance_world_time(date,text,text,text) from public,anon,authenticated;
grant execute on function public.tlr_advance_world_time(date,text,text,text) to service_role;

commit;
